### PR TITLE
Add to the doc

### PR DESCRIPTION
**Pull request by pksjce**
Just updating the readme.
Does the api seem too awkward?

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Yeah looks a bit weird, forgot about that in the previous PR though. 

```
const findMatches = require('js-cpa');
findMatches(filename);
```

We can keep the old code for `bin.js` and keep the wrapper in tests alone.

**Comment by pksjce** [comment]
But then there will be no way of using it as node API no?

**Comment by vigneshshanmugam** [comment]
why not? we can still pass the filename 

```
const findMatches = require('js-cpa');
const bundle = path.join("example", "bundle.js");
findMatches(bundle);
```

**Comment by pksjce** [comment]
Hey, got your idea. Made the change here. Will open next PR after we are done with this! Thanks for your patience.

**Review by vigneshshanmugam — APPROVED** [review]

**Comment by vigneshshanmugam** [comment]
Cool, Looks neat! Thanks once again 👍

**Pull request merged**
