### PR TITLE
Make snapshots independent of absolute path

### PR DESCRIPTION
**Pull request by pksjce**
Hey! Love the idea of the project. 
Cloned it and tried to run the tests and they broke with snapshot errors.
Turns out the reporter shows absolute path in the report and that corresponds to your machine.

Fixed this by having the reporter only output given filepath. 
Not sure if this behaviour is consistent with your vision, but need somehow to make the tests work same on all machines. Open to other solutions

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
@pksjce Thanks for the PR. Good catch 👍

We can mock the path.resolve in the test case and print only the file. We can follow the same way like mocking `chalk` for the reporter. https://github.com/vigneshshanmugam/js-cpa/tree/master/test/__mocks__

Thoughts?

**Comment by pksjce** [comment]
Hey great idea! 
 * Refactored the filearg and ast code and created an apiwrapper
 * Added mock for path

What do you think? `findSimilar` is just a name I gave. I'm not too attached to it.

**Comment by vigneshshanmugam** [comment]
Awesome, code looks neat. Can we rename it as findMatches since the o/p aligns more with matches?  Sorry for that!

**Review by vigneshshanmugam — APPROVED** [review]

**Comment by pksjce** [comment]
Done!

**Comment by vigneshshanmugam** [comment]
Thanks a lot :)

**Pull request merged**
